apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: {{ .Values.storageAccount.name }}
  AZURE_STORAGE_KEY: {{ .Values.storageAccount.key }}